apiVersion: v1
kind: ConfigMap
metadata:
  name: keda-auto-scale-rules
  namespace: monitoring
data:
  namespace: area
  namePrefix: international-
  labelKey: keda-app
  labelValue: true
  minReplica: "1"
  maxReplica: "5"
  cpuThreshold: "80"
